# components.py

components = {
    "structure": [
        {
            "name": "Rock",
            "prix": 2,
            "durability": 4,
            "isolation": 2,
            "energy_consumption": None,
            "eco_friendly": 5,
            "image": "image/4.jpg",
            "claimed": False,
        },
        {
            "name": "Beton Cellulaire",
            "prix": 4,
            "durability": 4,
            "isolation": 4,
            "energy_consumption": None,
            "eco_friendly": 3,
            "image": "image/5.jpg",
            "claimed": False,
        },
        {
            "name": "Bois",
            "prix": 4,
            "durability": 3,
            "isolation": 5,
            "energy_consumption": None,
            "eco_friendly": 4,
            "image": "image/6.jpg",
            "claimed": False,
        },
        {
            "name": "Brique",
            "prix": 5,
            "durability": 4,
            "isolation": 2,
            "energy_consumption": None,
            "eco_friendly": 3,
            "image": "image/7.jpg",
            "claimed": False,
        },
    ],
    "interior_system": [
        {
            "name": "Electrical Heating System",
            "prix": 2,
            "durability": 4,
            "isolation": None,
            "energy_consumption": 1,
            "eco_friendly": 2,
            "image": "image/9.jpg",
            "claimed": False,
        },
        {
            "name": "Heat Pump",
            "prix": 4,
            "durability": 4,
            "isolation": None,
            "energy_consumption": 4,
            "eco_friendly": 3,
            "image": "image/10.jpg",
            "claimed": False,
        },
        {
            "name": "Ductless Mini-Split",
            "prix": 4,
            "durability": 4,
            "isolation": None,
            "energy_consumption": 5,
            "eco_friendly": 2,
            "image": "image/11.jpg",
            "claimed": False,
        },
        {
            "name": "In-Floor Heating",
            "prix": 2,
            "durability": 5,
            "isolation": None,
            "energy_consumption": 4,
            "eco_friendly": 2,
            "image": "image/12.jpg",
            "claimed": False,
        },
        {
            "name": "Forced Air",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "energy_consumption": 3,
            "eco_friendly": 3,
            "image": "image/13.jpg",
            "claimed": False,
        },
        {
            "name": "Hybrid Heat System",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "energy_consumption": 5,
            "eco_friendly": 4,
            "image": "image/14.jpg",
            "claimed": False,
        },
    ],
    "kitchen": [
        {
            "name": "Kitchen Wood",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/16.jpg",
            "claimed": False,
        },
        {
            "name": "Kitchen Quartz",
            "prix": 4,
            "durability": 5,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/17.jpg",
            "claimed": False,
        },
        {
            "name": "Kitchen Ceramic",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 2,
            "image": "image/18.jpg",
            "claimed": False,
        },
        {
            "name": "Kitchen Marble",
            "prix": 1,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 1,
            "image": "image/19.jpg",
            "claimed": False,
        },
        {
            "name": "Kitchen Wood Veneer",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/20.jpg",
            "claimed": False,
        },
        {
            "name": "Kitchen MDF",
            "prix": 4,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/21.jpg",
            "claimed": False,
        },
    ],
    "bathroom": [
        {
            "name": "Bathroom Wood",
            "prix": 2,
            "durability": 2,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/23.jpg",
            "claimed": False,
        },
        {
            "name": "Bathroom Quartz",
            "prix": 4,
            "durability": 5,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/24.jpg",
            "claimed": False,
        },
        {
            "name": "Bathroom Ceramic",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 2,
            "image": "image/25.jpg",
            "claimed": False,
        },
        {
            "name": "Bathroom Marble",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 1,
            "image": "image/26.jpg",
            "claimed": False,
        },
        {
            "name": "Bathroom Wood Veneer",
            "prix": 3,
            "durability": 2,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/27.jpg",
            "claimed": False,
        },
        {
            "name": "Bathroom MDF",
            "prix": 3,
            "durability": 2,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/28.jpg",
            "claimed": False,
        },
    ],
    "laundry_room": [
        {
            "name": "Laundry Room Wood",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/29.jpg",
            "claimed": False,
        },
        {
            "name": "Laundry Room Quartz",
            "prix": 4,
            "durability": 5,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/30.jpg",
            "claimed": False,
        },
        {
            "name": "Laundry Room Ceramic",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/31.jpg",
            "claimed": False,
        },
        {
            "name": "Laundry Room Marble",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 2,
            "image": "image/32.jpg",
            "claimed": False,
        },
        {
            "name": "Laundry Wood Veneer",
            "prix": 3,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/33.jpg",
            "claimed": False,
        },
        {
            "name": "Laundry MDF",
            "prix": 4,
            "durability": 2,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/34.jpg",
            "claimed": False,
        },
    ],
    "living_room": [
        {
            "name": "Living Room Industrial",
            "prix": 3,
            "durability": 5,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/36.jpg",
            "claimed": False,
        },
        {
            "name": "Living Room Country House",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/37.jpg",
            "claimed": False,
        },
        {
            "name": "Living Room Boho",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 5,
            "image": "image/38.jpg",
            "claimed": False,
        },
        {
            "name": "Living Room Japandi",
            "prix": 3,
            "durability": 5,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/39.jpg",
            "claimed": False,
        },
        {
            "name": "Living Room Midcentury",
            "prix": 4,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/40.jpg",
            "claimed": False,
        },
        {
            "name": "Living Room Fashion Focal",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 2,
            "image": "image/41.jpg",
            "claimed": False,
        },
    ],
    "master_bedroom": [
        {
            "name": "Master Bedroom Industrial",
            "prix": 3,
            "durability": 5,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/43.jpg",
            "claimed": False,
        },
        {
            "name": "Master Bedroom Country House",
            "prix": 3,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/44.jpg",
            "claimed": False,
        },
        {
            "name": "Master Bedroom Boho",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 5,
            "image": "image/45.jpg",
            "claimed": False,
        },
        {
            "name": "Master Bedroom Japandi",
            "prix": 3,
            "durability": 5,
            "isolation": None,
            "eco_friendly": 4,
            "image": "image/46.jpg",
            "claimed": False,
        },
        {
            "name": "Master Bedroom Midcentury",
            "prix": 4,
            "durability": 4,
            "isolation": None,
            "eco_friendly": 3,
            "image": "image/47.jpg",
            "claimed": False,
        },
        {
            "name": "Master Bedroom Fashion Focal",
            "prix": 2,
            "durability": 3,
            "isolation": None,
            "eco_friendly": 2,
            "image": "image/48.jpg",
            "claimed": False,
        },
    ],
    "children_bedroom": [
        {
            "name": "Children Bedroom Minecraft",
            "prix": None,
            "durability": None,
            "isolation": None,
            "eco_friendly": None,
            "image": "image/50.jpg",
            "claimed": False,
        },
        {
            "name": "Children Bedroom Hello Kitty",
            "prix": None,
            "durability": None,
            "isolation": None,
            "eco_friendly": None,
            "image": "image/51.jpg",
            "claimed": False,
        },
        {
            "name": "Children Bedroom Football",
            "prix": None,
            "durability": None,
            "isolation": None,
            "eco_friendly": None,
            "image": "image/52.jpg",
            "claimed": False,
        },
        {
            "name": "Children Bedroom Pirate",
            "prix": None,
            "durability": None,
            "isolation": None,
            "eco_friendly": None,
            "image": "image/53.jpg",
            "claimed": False,
        },
    ],
}
